export const clubs = [
  {
    id: "robot-hust",
    name: "CLB Lập trình & Robot HUST",
    category: "Công nghệ",
    members: 850,
    status: "ACTIVE",
    admin: "Nguyễn Văn A",
    description:
      "Nơi kết nối sinh viên yêu thích lập trình, robotics và AI ứng dụng.",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "guitar",
    name: "CLB Guitar & Acoustic",
    category: "Nghệ thuật",
    members: 156,
    status: "ACTIVE",
    admin: "Quân Admin",
    description:
      "Không gian luyện tập, biểu diễn và lan tỏa âm nhạc trong trường.",
    image:
      "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "green-hub",
    name: "Dự án Xanh - Green Hub",
    category: "Tình nguyện",
    members: 250,
    status: "PENDING",
    admin: "Lê Thị Mai Anh",
    description: "Nhóm sinh viên hành động vì môi trường và lối sống bền vững.",
    image:
      "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "debate",
    name: "CLB Tranh biện & Kỹ năng",
    category: "Kỹ năng mềm",
    members: 98,
    status: "ACTIVE",
    admin: "Trần Hoàng Long",
    description: "Rèn luyện tư duy phản biện, thuyết trình và lãnh đạo.",
    image:
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
  },
];
export const events = [
  {
    id: "tech-summit",
    title: "Hội nghị Thượng đỉnh Công nghệ Sinh viên 2026",
    club: "CLB Lập trình & Robot HUST",
    date: "15/12/2026",
    time: "08:00 - 17:00",
    location: "Hội trường A5",
    status: "PUBLISHED",
    registered: 320,
    capacity: 500,
    points: 100,
  },
  {
    id: "uiux",
    title: "Workshop: UI/UX Essentials 2026",
    club: "CLB Guitar & Acoustic",
    date: "24/10/2026",
    time: "14:00",
    location: "Hội trường A2",
    status: "PUBLISHED",
    registered: 85,
    capacity: 100,
    points: 50,
  },
  {
    id: "music-night",
    title: "Đêm nhạc Hội ngộ Vươn xa 2026",
    club: "CLB Guitar & Acoustic",
    date: "22/12/2026",
    time: "19:30",
    location: "Sân trung tâm",
    status: "DRAFT",
    registered: 40,
    capacity: 300,
    points: 30,
  },
];
export const members = [
  {
    id: "sv001",
    name: "Nguyễn Văn A",
    code: "SE180001",
    role: "PRESIDENT",
    status: "ACTIVE",
    points: 850,
    joinedAt: "12/03/2024",
  },
  {
    id: "sv002",
    name: "Trần Thị B",
    code: "SE180112",
    role: "MEMBER",
    status: "ACTIVE",
    points: 620,
    joinedAt: "05/04/2024",
  },
  {
    id: "sv003",
    name: "Lê Minh C",
    code: "SE181230",
    role: "MEMBER",
    status: "PENDING",
    points: 320,
    joinedAt: "18/05/2024",
  },
  {
    id: "sv004",
    name: "Phạm Hoàng D",
    code: "SE182221",
    role: "VICE_PRESIDENT",
    status: "ACTIVE",
    points: 790,
    joinedAt: "20/06/2024",
  },
];
export const proposals = [
  {
    id: "aic",
    name: "CLB Trí tuệ Nhân tạo - AIC",
    founder: "Nguyễn Minh Tuấn",
    faculty: "Khoa CNTT",
    date: "12/03/2026",
    status: "PENDING",
    score: 8.7,
  },
  {
    id: "digital-art",
    name: "Câu lạc bộ Nghệ thuật số & Media",
    founder: "Phạm Thu Thảo",
    faculty: "Liên khoa",
    date: "10/03/2026",
    status: "NEED_REVISION",
    score: 7.4,
  },
  {
    id: "green",
    name: "Dự án Xanh - Green Hub",
    founder: "Lê Thị Mai Anh",
    faculty: "Liên khoa",
    date: "08/03/2026",
    status: "APPROVED",
    score: 9.1,
  },
];
export const users = [
  {
    id: "u1",
    name: "Nguyễn Văn Khải",
    email: "khai.nv@university.edu.vn",
    role: "STUDENT",
    status: "ACTIVE",
    clubs: 3,
  },
  {
    id: "u2",
    name: "Quân Admin",
    email: "quan.admin@university.edu.vn",
    role: "CLUB_ADMIN",
    status: "ACTIVE",
    clubs: 1,
  },
  {
    id: "u3",
    name: "Mai Anh",
    email: "maianh@university.edu.vn",
    role: "STUDENT",
    status: "LOCKED",
    clubs: 2,
  },
];
export const auditLogs = [
  [
    "12/03/2026 09:20",
    "SYSTEM_ADMIN",
    "Phê duyệt đề xuất CLB Green Hub",
    "SUCCESS",
  ],
  [
    "12/03/2026 10:15",
    "CLUB_ADMIN",
    "Duyệt yêu cầu tham gia của SE180112",
    "SUCCESS",
  ],
  ["13/03/2026 08:00", "SYSTEM", "Gửi thông báo bảo trì định kỳ", "INFO"],
  [
    "13/03/2026 14:30",
    "CLUB_ADMIN",
    "Hủy sự kiện do trùng lịch hội trường",
    "WARNING",
  ],
];
